Web/FitForLife.Web/Areas/Trainer/Controllers/MyClientsController.cs
namespace FitForLife.Areas.Trainer.Controllers
{
    using FitForLife.Data.Models.Enums;
    using FitForLife.Services.Data.Exercises;
    using FitForLife.Services.Data.Trainers;
    using FitForLife.Services.Data.WorkoutPlan;
    using FitForLife.Web.ViewModels.Users;
    using FitForLife.Web.ViewModels.WorkoutPlan;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class MyClientsController : TrainerController
    {
        private readonly ITrainersService trainersService;
        private readonly IExercisesService exercisesService;
        private readonly IWorkoutPlanService workoutPlanService;

        public MyClientsController(ITrainersService trainersService, IExercisesService exercisesService , IWorkoutPlanService workoutPlanService)
        {
            this.trainersService = trainersService;
            this.exercisesService = exercisesService;
            this.workoutPlanService = workoutPlanService;
        }

        public async Task<IActionResult> Index()
        {
            var trainerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var classViewModel = new AllClientsViewModel
            {
                Clients = await this.trainersService.GetAllClients<UsersViewModel>(trainerId)
            };
            //var classViewModel = this.trainersService.GetAllClients<UsersViewModel>(trainerId);
            //;
            return this.View(classViewModel);
        }
        public async Task<IActionResult> PlanDetails(string planId)
        {
            var viewModel = await this.workoutPlanService.GetWorkoutPlanById<WorkoutPlanViewModel>(planId);
            return this.View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> AddProgramIndex(string clientId)
        {
            var exercises = await this.exercisesService.GetAllExerciseAsync<ExerciseViewModel>();
            this.ViewData["Exercises"] = new SelectList(exercises, nameof(ExerciseViewModel.Id),nameof(ExerciseViewModel.Name), nameof(ExerciseViewModel.Difficulty));
            this.ViewData["ClientId"] = clientId;
            return this.View();
        }
        [HttpPost]
        public async Task<IActionResult> AddProgram(AllTrainingDaysInput model)
        {
            await this.workoutPlanService.AddProgramAsync(model);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteProgram(string Id)
        {
            await this.workoutPlanService.DeletePlan(Id);
            return RedirectToAction("Index");
        }
    }
}

Web/FitForLife.Web/Areas/Trainer/Views/MyClients/AddProgramIndex.cshtml
@model FitForLife.Web.ViewModels.WorkoutPlan.AllTrainingDaysInput

@{
    ViewData["Title"] = "Add Program";
    var Exercises = this.ViewData["Exercises"] as SelectList;
    var clientId = this.ViewData["ClientId"];
}

<form action="/" method="post">
</form>
<div class="col-auto">
    <h2>New Program</h2>
    <form method="post" enctype="multipart/form-data" class="pt-4">
        @*<div class="form-group">
                <label class="col-auto">Difficulty</label>
                <div class="col-auto">
                    <select asp-for="@Model.Difficulty" class="form-control" asp-items="@Diffliculty">
                    </select>
                    <span asp-validation-for="Difficulty" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-auto col-form-label">Image</label>
                <div class="col-auto">
                    <input type="number" asp-for="@Model.DaysInWeek" class="form-control"/>
                    <span asp-validation-for="DaysInWeek" class="text-danger"></span>
                </div>
            </div>*@
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Monday</th>
                    <th scope="col">Tuesday</th>
                    <th scope="col">Wednesday</th>
                    <th scope="col">Thursday</th>
                    <th scope="col">Friday</th>
                    <th scope="col">Saturday</th>
                    <th scope="col">Sunday</th>
                </tr>
            </thead>

            <tbody>

                @for (int i = 0; i < 7; i++)
                {
                    <tr>
                        @for (int u = 0; u < 7; u++)
                        {
                            <td>
                                <select asp-for="@Model.TrainingDayInputs[u].Exercises[i].Id" class="form-control" asp-items=@Exercises>
                                </select>
                            </td>
                        }
                    </tr>
                }

            </tbody>
        </table>
        <div class="form-group row">
            <div class="col-sm-6 text-right">
                <input asp-for="UserId" value="@clientId" hidden />
                <button type="submit" class="btn btn-success"
                        asp-area="Trainer" asp-controller="MyClients" asp-action="AddProgram">
                    Add Program
                </button>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-danger" asp-area="Trainer" asp-controller="MyClients" asp-action="Index">Cancel</a>
            </div>
        </div>
    </form>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Web/FitForLife.Web/Areas/Trainer/Views/MyClients/Index.cshtml
@model FitForLife.Web.ViewModels.Users.AllClientsViewModel

@{ 
    this.ViewData["Title"] = "Trainer Dashboard"; 
    }


<div class="container" style="margin-top: 5rem">
    <h3>My Clients</h3>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Profile Picture</th>
                <th scope="col">Age</th>
                <th scope="col">Workout Program</th>
                <th scope="col">Add New Program</th>
                <th scope="col">Delete Program</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var viewModel in Model.Clients)
            {
                <tr>
                    <td>@viewModel.Client.FirstName @viewModel.Client.LastName</td>
                    <td><img class="align-self-center" src="@viewModel.Client.ProfilePictureUrl" style="width:180px;height:120px;"></td>
                    <td>@viewModel.Client.Age</td>
                    <td>
                        @if (viewModel.Client.WorkoutPlanId != null)
                        {
                        <form method="post">
                            <input type="text" name="planId" value="@viewModel.Client.WorkoutPlanId" hidden />
                            <button type="submit" class="btn btn-success btn-sm"
                                    asp-area="Trainer" asp-controller="MyClients" asp-action="PlanDetails">
                                Details
                            </button>
                        </form>
                        }
                        @if (viewModel.Client.WorkoutPlanId == null)
                        {
                            <h5>Do not have program yet</h5>
                        }
                    </td>
                    <td>
                        @if (viewModel.Client.WorkoutPlanId == null)
                        {
                            <form method="post">
                                <input type="text" name="clientId" value="@viewModel.ClientId" hidden />
                                <button type="submit" class="btn btn-success btn-sm"
                                        asp-area="Trainer" asp-controller="MyClients" asp-action="AddProgramIndex">
                                    Add Program
                                </button>
                            </form>
                        }
                        @if (viewModel.Client.WorkoutPlanId != null)
                        {
                            <h5>The Client have program already</h5>
                        }
                    </td>
                    <td>
                        @if (viewModel.Client.WorkoutPlanId != null)
                        {
                            <form method="post">
                                <button type="submit" class="btn btn-danger btn-sm"
                                        asp-area="Trainer" asp-controller="MyClients" asp-action="DeleteProgram" asp-route-id="@viewModel.Client.WorkoutPlanId">
                                    Delete
                                </button>
                            </form>
                        }
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

Web/FitForLife.Web/Areas/Trainer/Views/MyClients/PlanDetails.cshtml
@model FitForLife.Web.ViewModels.WorkoutPlan.WorkoutPlanViewModel
@{ 
    var days = Enum.GetValues(typeof(DayOfWeek)).Cast<DayOfWeek>().ToList();
    var dayCount = 1;
}
<div class="container" style="margin-top: 5rem">
    <h2>Diffilculty: @Model.Difficulty</h2>
    <table class="table table-bordered table-striped">
        <tbody>
           
            @foreach (var trainingDay in Model.TrainingDays)
            {
                var count = 0;

                <tr>
                    <th>
                        @days[dayCount]
                    </th>
                    @for (int i = 0; i < Model.TrainingDays.Length; i++)
                    {

                        if (trainingDay.Exercises.Length > i)
                        {
                            if (i <= trainingDay.Exercises.Length)
                            {

                                <td>
                                    <a href="@trainingDay.Exercises[count].VideoUrl">@trainingDay.Exercises[count].Name</a>   
                                </td>
                                count++;
                            }

                        }
                        else
                        {
                            count = 0;
                            <td>REST</td>
                        }
                    }
                </tr>
                dayCount++;
                if (dayCount==7)
                {
                    dayCount = 0;
                }
            }

        </tbody>
    </table>
</div>