Web/FitForLife.Web/Areas/Administration/Controllers/EventsController.cs
namespace FitForLife.Areas.Administration.Controllers
{
    using FitForLife.Data.Models;
    using FitForLife.Services.Data.Classes;
    using FitForLife.Services.Data.Events;
    using FitForLife.Web.ViewModels.Classes;
    using FitForLife.Web.ViewModels.Events;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class EventsController :AdministrationController
    {
        private readonly IEventService eventService;
        private readonly IClassesService classesService;

        public EventsController(IEventService eventService, IClassesService classesService)
        {
            this.eventService = eventService;
            this.classesService = classesService;
        }
        public async Task<IActionResult> Index()
        {
            var viewModel = new AllEventsViewModel
            {
                Events = await this.eventService.GetAllEventsAsync<EventViewModel>(),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> AddEvent()
        {
            var classViews = await this.classesService.GetAllAsync<ClassViewModel>();
            this.ViewData["Events"] = new SelectList(classViews, 
                nameof(ClassViewModel.Id), 
                nameof(ClassViewModel.Name));
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEvent(EventInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            
            await this.eventService.AddAsync(model.ClassId, model.StartEvent, model.EndEvent, model.AvailableSpots, model.Description);
            return this.RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteEvent(string Id)
        {
            await this.eventService.DeleteAsync(Id);

            return this.RedirectToAction("Index");
        }
    }
}

Web/FitForLife.Web/Controllers/AppointmentsController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Services.Data.Events;
    using FitForLife.Web.ViewModels;
    using FitForLife.Web.ViewModels.Events;
    using Microsoft.AspNetCore.Mvc;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class AppointmentsController : Controller
    {
        private readonly IEventService eventServices;

        public AppointmentsController(IEventService eventServices)
        {
            this.eventServices = eventServices;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new AllEventsViewModel
            {
                Events = await this.eventServices.GetAllEventsAsync<EventViewModel>()
            };
            if (viewModel == null)
            {
                var error = new ErrorViewModel();
                return this.View(error);
            }
            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(string Id)
        {
            var viewModel = await this.eventServices.GetByIdAsync<EventViewModel>(Id);

            if (this.User.Identity.IsAuthenticated)
            {
                return this.View(viewModel);
            }
            return Redirect("/Identity/Account/Login");

        }
        public async Task<IActionResult> AddUserToEvent(string eventId)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var @event = await eventServices.AddUserToEvent(userId,eventId);
                if (@event == null)
                {
                    return Redirect("/Cards/Index");
                }
                return Redirect("/Identity/Account/Manage/MyCard");
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }

        }
    }
}

Web/FitForLife.Web/Views/Appointments/Details.cshtml
@model FitForLife.Web.ViewModels.Events.EventViewModel

<section class="EventView">
    <div class="container">
        <h1 style="margin: 2%; text-align: center;">Event</h1>
        <div>
            <div class="form-group text-center">
                <img src="@Model.Class.PictureUrl" class="img-fluid">
            </div>
            <div class="form-group">
                <label>Class</label>
                <input type="text" readonly class="form-control" value="@Model.Class.Name">
            </div>
            <div class="form-group">
                <label>Begining</label>
                <input type="datetime" readonly class="form-control" value="@Model.StartEvent">
            </div>
            <div class="form-group">
                <label>End</label>
                <input type="datetime" readonly class="form-control" value="@Model.EndEvent">
            </div>
            <div class="form-group">
                <label>Description</label>
                <input type="text" readonly class="form-control" value="@Model.Description">
            </div>
            @if (Model.AvailableSpots > 0)
            {
                <div class="form-group">
                    <label>Available Spots</label>
                    <input type="number" readonly class="form-control" value="@Model.AvailableSpots">
                </div>
                <div class="btn btn-info btn-lg">
                    <form asp-action="AddUserToEvent" asp-controller="Appointments" method="post">
                        <input type="text" name="EventId" value="@Model.Id" hidden />
                        <button type="submit" class="btn btn-danger-gradiant rounded-pill text-white btn-md border-0">
                            Join!
                        </button>
                    </form>
                </div>
            }
            @if (Model.AvailableSpots == 0)
            {
                <h3 style="color: #ffffff"> Sorry , no more available spot for this event!</h3>    
            }

        </div>
    </div>
</section>

Web/FitForLife.Web/Views/Appointments/Index.cshtml
<link href="~/css/Calendar.css" rel="stylesheet" />
<script src="~/js/Calendar.js"></script>
<!------ Include the above in your HEAD tag ---------->

@model FitForLife.Web.ViewModels.Events.AllEventsViewModel
<div class="container" style="margin-top: 50px">
    <h1 class="title text-center"> @DateTime.UtcNow.ToString("M") </h1>
    <div class="calendar" data-toggle="calendar">
        <div class="row">
            @for (int i = 0; i < 7; i++)
            {
            <div class="col-xs-12 calendar-day">
                <span>@DateTime.UtcNow.AddDays(i).Day.ToString() @DateTime.UtcNow.AddDays(i).ToString("ddd")</span>
                <time datetime="@DateTime.UtcNow.AddDays(i).ToString("d")">@DateTime.UtcNow.AddDays(i).Day</time>
                @foreach (var @events in Model.Events)
                {
                    if (@events.StartEvent.Date == @DateTime.UtcNow.AddDays(i).Date)
                    {
            <partial name="_Event" for="@events" />}
                            }

            </div>
             }
        </div>
        <div class="row">
            @for (int i = 7; i < 14; i++)
            {
            <div class="col-xs-12 calendar-day">
                <span>@DateTime.UtcNow.AddDays(i).Day.ToString() @DateTime.UtcNow.AddDays(i).ToString("ddd")</span>
                <time datetime="@DateTime.UtcNow.AddDays(i).ToString("d")">@DateTime.UtcNow.AddDays(i).Day</time>
                @foreach (var @events in Model.Events)
                {
                    if (@events.StartEvent.Date == @DateTime.UtcNow.AddDays(i).Date)
                    {
            <partial name="_Event" for="@events" />}
    }
            </div>
             }
        </div>
        <div class="row">
            @for (int i = 14; i < 21; i++)
             {
            <div class="col-xs-12 calendar-day">
                <span>@DateTime.UtcNow.AddDays(i).Day.ToString() @DateTime.UtcNow.AddDays(i).ToString("ddd")</span>
                <time datetime="@DateTime.UtcNow.AddDays(i).ToString("d")">@DateTime.UtcNow.AddDays(i).Day</time>
                @foreach (var @events in Model.Events)
                {
                    if (@events.StartEvent.Date == @DateTime.UtcNow.AddDays(i).Date)
                    {
            <partial name="_Event" for="@events" />}
    }
            </div>  
             }
        </div>
        <div class="row">
            @for (int i = 21; i < 28; i++)
             {
            <div class="col-xs-12 calendar-day">
                <span>@DateTime.UtcNow.AddDays(i).Day.ToString() @DateTime.UtcNow.AddDays(i).ToString("ddd")</span>
                <time datetime="@DateTime.UtcNow.AddDays(i).ToString("d")">@DateTime.UtcNow.AddDays(i).Day</time>
                @foreach (var @events in Model.Events)
                {
                    if (@events.StartEvent.Date == @DateTime.UtcNow.AddDays(i).Date)
                    {
            <partial name="_Event" for="@events" />                    }
                            }
            </div>
             }
        </div>
        <div class="row">
            @for (int i = 28; i < 35; i++)
            {
            <div class="col-xs-12 calendar-day">
                <span>@DateTime.UtcNow.AddDays(i).Day.ToString() @DateTime.UtcNow.AddDays(i).ToString("ddd")</span>
                <time datetime="@DateTime.UtcNow.AddDays(i).ToString("d")">@DateTime.UtcNow.AddDays(i).Day</time>
                @foreach (var @events in Model.Events)
                {
                    if (@events.StartEvent.Date == @DateTime.UtcNow.AddDays(i).Date)
                    {
            <partial name="_Event" for="@events" />}
                            }
            </div>
            }
        </div>
    </div>
</div>

Web/FitForLife.Web/Views/Appointments/_Event.cshtml
@model FitForLife.Web.ViewModels.Events.EventViewModel

<div class="events">
    <div class="event">
        <h4>@Model.Class.Name</h4>
        <p>@Model.StartEvent.ToString("t") - @Model.EndEvent.ToString("t")</p>
        <form asp-action="Details" asp-controller="Appointments" asp-route-id="@Model.Id" method="get">
            <button type="submit" class="btn btn-info rounded-pill text-dark btn-sm border-0">
                Read More
            </button>
        </form>
    </div>
</div>