Web/FitForLife.Web/Controllers/CardsController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Data.Models;
    using FitForLife.Services.Data.Cards;
    using FitForLife.Services.Data.Users;
    using FitForLife.Web.ViewModels.Cards;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.ComponentModel.DataAnnotations;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class CardsController : Controller
    {
        private readonly ICardsService cardsService;
        private readonly IUserService UserService;

        public CardsController(ICardsService cardsService, IUserService userService)
        {
            this.cardsService = cardsService;
            UserService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var cardsViewModel = new AllCardsViewModel
            {
                Cards = await this.cardsService.GetAllAsync<CardsViewModel>()
            };
            return View(cardsViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> BuyCard(int cardId)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                await UserService.AddCardToUser(userId, cardId);
                return Redirect("/Identity/Account/Manage/MyCard");
            }
            else
            {
                return Redirect("/Identity/Account/Login");
            }
        }
    }
}

Web/FitForLife.Web/Controllers/ClassesController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Services.Data.Classes;
    using FitForLife.Web.ViewModels.Classes;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class ClassesController : Controller
    {
        private readonly IClassesService classesService;

        public ClassesController(IClassesService classesService)
        {
            this.classesService = classesService;
            
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var viewModel = new AllClassesViewModel
            {
                Classes = await this.classesService.GetAllAsync<ClassViewModel>()
            };
            return this.View(viewModel);
        }
        
        public async Task<IActionResult> Details(int Id)
        {
            var viewModel = await this.classesService.GetByIdAsync<DetailsClassViewModel>(Id);

            if (this.User.Identity.IsAuthenticated)
            {
                return this.View(viewModel);
            }
            return Redirect("/Identity/Account/Login");
            
        }
    }
}

Web/FitForLife.Web/Controllers/HomeController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Models;
    using FitForLife.Services.Data.Cards;
    using FitForLife.Services.Data.Classes;
    using FitForLife.Services.Data.Trainers;
    using FitForLife.Web.ViewModels.Cards;
    using FitForLife.Web.ViewModels.Classes;
    using FitForLife.Web.ViewModels.Home;
    using FitForLife.Web.ViewModels.Trainers;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using Microsoft.Extensions.Logging;
    using System;
    using System.Diagnostics;
    using System.Threading.Tasks;

    using static FitForLife.Common.GlobalConstants.Cache;

    public class HomeController : Controller

    {
        private readonly IClassesService classesService;
        private readonly ITrainersService trainersService;
        private readonly ICardsService cardsService;
        private readonly ILogger<HomeController> _logger;
        private readonly IMemoryCache cache;

        public HomeController(ILogger<HomeController> logger, IClassesService classesService, ICardsService cardsService, IMemoryCache cache, ITrainersService trainersService)
        {
            _logger = logger;
            this.classesService = classesService;
            this.cardsService = cardsService;
            this.cache = cache;
            this.trainersService = trainersService;
        }

        public async Task<IActionResult> Index()
        {
            var allView = this.cache.Get<HomeViewModels>(HomeViewMemoryCache);
            if (allView == null)
            {
                var classViewModel = new HomeAllClassViewModel
                {
                    Classes = await this.classesService.GetAllAsync<HomeClassViewModel>(3)
                };
                var cardsViewModel = new AllCardsViewModel
                {
                    Cards = await this.cardsService.GetAllAsync<CardsViewModel>()
                };
                var trainerViewModel = new AllTrainersViewModel
                {
                    Trainers = await this.trainersService.GetAllTrainersAsync<TrainerViewModel>(3)
                };
                allView = new HomeViewModels
                {
                    Cards = cardsViewModel,
                    Classes = classViewModel,
                    Trainers = trainerViewModel,
                };
                var cacheOptions = new MemoryCacheEntryOptions()
                     .SetAbsoluteExpiration(TimeSpan.FromMinutes(10));

                this.cache.Set(HomeViewMemoryCache, allView, cacheOptions);
            }
            return View(allView);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [Route("/Home/Error/404")]
        public IActionResult Error404()
        {
            return this.View();
        }

        [Route("/Home/Error/{code:int}")]
        public IActionResult Error(int code)
        {
            // Could handle different codes here
            // or just return the default error view
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/FitForLife.Web/Controllers/TrainersController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Services.Data.Trainers;
    using FitForLife.Web.ViewModels.Trainers;
    using Microsoft.AspNetCore.Mvc;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class TrainersController : Controller
    {
        private readonly ITrainersService trainersService;

        public TrainersController(ITrainersService trainersService)
        {
            this.trainersService = trainersService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var viewModel = new AllTrainersViewModel
            {
                Trainers = await this.trainersService.GetAllTrainersAsync<TrainerViewModel>()
            };
            if (viewModel == null)
            {
                return new StatusCodeResult(404);
            }
            return this.View(viewModel);
        }
        public async Task<IActionResult> Details(string Id)
        {
            var trainerView =await this.trainersService.GetTrainerById<TrainerViewModel>(Id);
            
            return this.View(trainerView);
        }
        [HttpPost]
        public async Task<IActionResult> AddUserToTrainer(string trainerId)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId==null)
            {
                return Redirect("/Identity/Account/Login");
            }
            await trainersService.AddUserToTrainer(trainerId, userId);
            return RedirectToAction("All");
        }

    }
}

Web/FitForLife.Web/Views/Home/Index.cshtml
@model FitForLife.Web.ViewModels.Home.HomeViewModels
@{
    ViewData["Title"] = "Home Page";
}
<div id="carouselExampleIndicators" class="carousel slide h-75" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="/img/thumb-1920-628886.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Join NOW !</h5>
                <p>Success usually comes to those who are too busy to be looking for it.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/thumb-1920-916103.jpg" alt="Second slide">
            <div id="mainCarouselCaption" class="carousel-caption d-none d-md-block">
                <h5>Don't waste time!'</h5>
                <p>The clock is ticking. Are you becoming the person you want to be?</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/img/geert-pieters-AfgJpWQH4lw-unsplash.jpg" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Become one of US!</h5>
                <p>All our dreams can come true if we have the courage to pursue them.</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<section class="team section">
    <div class="container">
        <h1 class="section-title">Our Team Section</h1>
        <div class="row">
            @foreach (var trainerView in Model.Trainers.Trainers)
            {
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="team-item">
                        <figure>
                            <img src="@trainerView.ProfilePictureUrl" alt="">
                            <figcaption>
                                <div class="info">
                                    <h3>@trainerView.FirstName @trainerView.LastName</h3>
                                    <p>@trainerView.Class.Name</p>
                                </div>
                                <div class="social"><a asp-controller="Trainers" asp-action="Details" asp-route-id="@trainerView.Id">Bio</a></div>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

<section class="team section">
    <div class="container-fluid" style="background-color: #677e8e">
        <h1 class="section-title">Our Classes </h1>
        <div class="row">
            @foreach (var classView in Model.Classes.Classes)
            {
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="team-item">
                        <figure>
                            <img src="@classView.PictureUrl" alt="">
                            <figcaption>
                                <div class="info">
                                    <h3>@classView.Name</h3>
                                    <p>@classView.Description.Substring(0, 50) ...</p>
                                </div>
                                <div class="social"><a asp-controller="Classes" asp-action="Index">See More</a></div>
                            </figcaption>
                        </figure>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<div class="pricing8 py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h3 class="mb-3">Pricing to make your Work Effective</h3>
                <h6 class="subtitle font-weight-normal">We offer 100% satisafaction and Money back Guarantee</h6>
            </div>
        </div>
        <!-- row  -->
        <div class="row mt-4">
            <!-- column  -->
            @foreach (var card in Model.Cards.Cards)
            {
                <div class="col-md-3 ml-auto pricing-box align-self-center">
                    <div class="card mb-4">
                        <div class="card-body p-4 text-center">
                            <h5 class="font-weight-normal">@card.Name</h5>
                            <sup>$</sup><span class="text-dark display-5">@card.Price</span>
                            <h6 class="font-weight-light font-14">/Month</h6>
                            <p class="mt-4">@card.Visits Visits</p>
                        </div>
                        <a class="btn btn-info-gradiant p-3 btn-block border-0 text-white" asp-action="Index" asp-controller="Cards">CHOOSE PLAN </a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>