Web/FitForLife.Web/Controllers/BlogsController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Services.Data;
    using FitForLife.Web.ViewModels.Blog;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using System.Linq;
    using System.Threading.Tasks;

    public class BlogsController : Controller
    {
        private readonly IBlogService blogService;

        public BlogsController(IBlogService blogService)
        {
            this.blogService = blogService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new AllBlogViewModel
            {
                Blogs = await this.blogService.GetAllAsync<BlogViewModel>()
            };
            return this.View(viewModel);

        }
        public async Task<IActionResult> Details(string Id)
        {
            var viewModel = await this.blogService.GetByIdAsync<BlogViewModel>(Id);
            return this.View(viewModel);

        }
        [HttpPost]
        public async Task<IActionResult> AddComment(BlogViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            await this.blogService.AddingCommentToPost(model.CommentInputModel.BlogId ,model.CommentInputModel.Author, model.CommentInputModel.Context);
            return Redirect(Url.RouteUrl("Index") +"/Blogs"+"/Details/" + model.Id);
        }
    }
}

Web/FitForLife.Web/Controllers/ClassesController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Services.Data.Classes;
    using FitForLife.Web.ViewModels.Classes;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class ClassesController : Controller
    {
        private readonly IClassesService classesService;

        public ClassesController(IClassesService classesService)
        {
            this.classesService = classesService;
            
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var viewModel = new AllClassesViewModel
            {
                Classes = await this.classesService.GetAllAsync<ClassViewModel>()
            };
            return this.View(viewModel);
        }
        
        public async Task<IActionResult> Details(int Id)
        {
            var viewModel = await this.classesService.GetByIdAsync<DetailsClassViewModel>(Id);

            if (this.User.Identity.IsAuthenticated)
            {
                return this.View(viewModel);
            }
            return Redirect("/Identity/Account/Login");
            
        }
    }
}

Web/FitForLife.Web/Controllers/TrainersController.cs
namespace FitForLife.Controllers
{
    using FitForLife.Services.Data.Trainers;
    using FitForLife.Web.ViewModels.Trainers;
    using Microsoft.AspNetCore.Mvc;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class TrainersController : Controller
    {
        private readonly ITrainersService trainersService;

        public TrainersController(ITrainersService trainersService)
        {
            this.trainersService = trainersService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var viewModel = new AllTrainersViewModel
            {
                Trainers = await this.trainersService.GetAllTrainersAsync<TrainerViewModel>()
            };
            if (viewModel == null)
            {
                return new StatusCodeResult(404);
            }
            return this.View(viewModel);
        }
        public async Task<IActionResult> Details(string Id)
        {
            var trainerView =await this.trainersService.GetTrainerById<TrainerViewModel>(Id);
            
            return this.View(trainerView);
        }
        [HttpPost]
        public async Task<IActionResult> AddUserToTrainer(string trainerId)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId==null)
            {
                return Redirect("/Identity/Account/Login");
            }
            await trainersService.AddUserToTrainer(trainerId, userId);
            return RedirectToAction("All");
        }

    }
}

Web/FitForLife.Web/Areas/Administration/Views/Shared/_AdminHeaderPartial.cshtml
<div>
    <a asp-area="" asp-controller="Home" asp-action="Index"><span>Fit4Life</span></a>
</div>

Web/FitForLife.Web/Areas/Administration/Views/Shared/_AdminLayout.cshtml
@using FitForLife.Common
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

     <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
     <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    
    @this.RenderSection("Styles", required: false)
</head>
<body>

    <div class="container">
        <!-- Menu -->
        <partial name="_AdminMenuPartial" />
        <div>

            <div class="text-center">
                <a style="color: #ff6a00" asp-area="" asp-controller="Home" asp-action="Index"><strong>BACK TO HOME PAGE</strong></a>
            </div>
            <hr class="bg-dark mx-4" style="height: 6px;" />
            <div class="d-flex" id="wrapper">

                <!-- Sidebar -->
                @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                {
                    <partial name="_AdminSidebarPartial" />
                }

                <!-- Page Content -->
                <div id="page-content-wrapper">
                    <div class="container">
                        <div class="col-12">
                            <main role="main">
                                @this.RenderBody()
                            </main>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <hr class="bg-dark mx-4" style="height: 6px;" />
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/FitForLife.Web/Areas/Administration/Views/Shared/_AdminMenuPartial.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="Logo" src="~/img/fit-4-life-fitness-logo.jpg"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
</header>

Web/FitForLife.Web/Areas/Administration/Views/Shared/_AdminSidebarPartial.cshtml
<!-- Sidebar -->
<div class="bg-light border border-secondary" id="sidebar-wrapper">
    <div class="sidebar-heading"><strong><u>Admin</u></strong></div>
    <div class="list-group list-group-flush">

        <a asp-area="Administration" asp-controller="Classes" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Classes</a>

        <a asp-area="Administration" asp-controller="Blogs" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Blogs</a>

        <a asp-area="Administration" asp-controller="Events" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Events</a>

        <a asp-area="Administration" asp-controller="Trainers" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Classes</a>
    </div>
</div>
<!-- /#sidebar-wrapper -->